name: 🏁 Build Portable MLIR Toolchain

on:
  workflow_call:
    inputs:
      llvm-project-ref:
        description: "llvm-project ref or tag (e.g., llvmorg-22.1.0)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  windows-2025:
    uses: ./.github/workflows/build-mlir-windows-runner.yml
    with:
      llvm-project-ref: ${{ inputs.llvm-project-ref }}
      runs-on: windows-2025

  windows-11-arm:
    uses: ./.github/workflows/build-mlir-windows-runner.yml
    with:
      llvm-project-ref: ${{ inputs.llvm-project-ref }}
      runs-on: windows-11-arm
