name: 🍎 Build Portable MLIR Toolchain

on:
  workflow_call:
    inputs:
      llvm-project-ref:
        description: "llvm-project ref or tag (e.g., llvmorg-23.1.0)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  macos-26:
    uses: ./.github/workflows/build-mlir-macos-runner.yml
    with:
      llvm-project-ref: ${{ inputs.llvm-project-ref }}
      runs-on: macos-26
