name: 🐧 Build Portable MLIR Toolchain

on:
  workflow_call:
    inputs:
      llvm-project-ref:
        description: "llvm-project ref or tag (e.g., llvmorg-22.1.0)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  ubuntu-24-04:
    uses: ./.github/workflows/build-mlir-linux-runner.yml
    with:
      llvm-project-ref: ${{ inputs.llvm-project-ref }}
      runs-on: ubuntu-24.04

  ubuntu-24-04-arm:
    uses: ./.github/workflows/build-mlir-linux-runner.yml
    with:
      llvm-project-ref: ${{ inputs.llvm-project-ref }}
      runs-on: ubuntu-24.04-arm
